apiVersion: v1
kind: Service
metadata:
  name: trustflow-app
  namespace: trustflow
spec:
  selector:
    app.kubernetes.io/name: trustflow-app
  ports:
    - name: http
      port: 80
      targetPort: http

