global:
  image:
    repository: quay.io/argoproj/argocd@sha256
    tag: "64e4239359438fb0ad42d46ae2061daa841ae52d4e63f94017929f7e26dd51b2"

dex:
  image:
    repository: ghcr.io/dexidp/dex@sha256
    tag: "5d0656fce7d453c0e3b2706abf40c0d0ce5b371fb0b73b3cf714d05f35fa5f86"

redis:
  image:
    repository: ecr-public.aws.com/docker/library/redis@sha256
    tag: "59b6e694653476de2c992937ebe1c64182af4728e54bb49e9b7a6c26614d8933"
  exporter:
    image:
      repository: ghcr.io/oliver006/redis_exporter@sha256
      tag: "33fd1d09c3ba5d2354bdedfad62b06ecc54f50680823b1cf801dac9e1fd9d387"

server:
  extensions:
    image:
      repository: quay.io/argoprojlabs/argocd-extension-installer@sha256
      tag: "d2b43c18ac1401f579f6d27878f45e253d1e3f30287471ae74e6a4315ceb0611"
    enabled: true
    extensionList:
      - name: extension-trivy
        env:
          - name: EXTENSION_URL
            value: https://github.com/mziyabo/argocd-trivy-extension/releases/latest/download/extension-trivy.tar
          - name: EXTENSION_CHECKSUM_URL
            value: https://github.com/mziyabo/argocd-trivy-extension/releases/latest/download/extension-trivy_checksums.txt
      - name: extension-trustflow
        env:
          - name: EXTENSION_URL
            value: https://github.com/amirmahdy/trustflow-argocd-extension/raw/refs/heads/master/dist/extension-trustflow.tar
